config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html 
  resources :lists do
    member do
      post :check
    end
  end
  root "lists#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  #validates_presence_of :title, :date, :description 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_list, :only => [:show, :edit, :update, :destroy, :check]
  def index
    @lists = List.all
    @list = List.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    # if @list.save
    #   respond_to do |format|
    #     # format.html
    #     format.js
    #   end
    # end

  end

  def edit

    respond_to do |format|
      format.js
    end
  end


  def update

    if @list.update(list_params)
      respond_to do |format|
        format.js
      end
    end
  end

  def destroy
    if  @list.destroy
      respond_to do |format|
        format.js
      end
    end
  end

  def check
    @list.update(check: !(@list.check))
  end



  private

  def list_params
    params.require(:list).permit(:title, :date, :description)
  end

  def find_list
    @list = List.find(params[:id])
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1><%= flash[:notice]%></h1>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list, :remote => true do |f| %>
  <div class="input-group">
  <%= f.text_area :title, :class => "form-control" %>
  <div class="input-group-addon">
      <button type="submit" class="my-btn btn-info glyphicon glyphicon-floppy-disk">
      </button>
  </div>
</div>
<% end %>

app/views/lists/_index.html.erb
<div class="container">
  <table class="table table-striped table.hover text-center">
    <tr>
      <td>Check</td>
      <td>Task</td>
      <td>Due Date</td>
      <td>Show</td>
      <td>Edit</td>
      <td>Delete</td>
    </tr>
    <% @lists.sort{|a,b| a.date <=> b.date}.each do |list|%>
      <tr>

        <td><%= check_box_tag :check, false, list.check, data: {url:check_list_path(list), method: :post, remote: true } %></td>

        <td> <%= list.title.capitalize %></td>
        <td><%= list.date %></td>
        <td><button class="btn btn-default" ><%= link_to "Show", list_path(list)%></button></td>
        <td><button type="button" class="btn btn-success"><%= link_to "Edit", edit_list_path(list)%></button></td>
        <td><button type="button" class="btn btn-warning"><%= link_to "Delete", list_path(list),method: :delete, data:{ confirm: "Are you sure?" } %></button>
          </td>
      </tr>
    <% end %>

  </table>

  <div class="text-center">
    <button class="btn btn-default"  type="submit"><%= link_to "New List", new_list_path %></button>
  </div>

</div>

app/views/lists/_tr.html.erb
    <td class="my-pointer">
        <span class="my-font glyphicon glyphicon-unchecked" aria-hidden="true" onclick="doneToggle()"></span>
        <span class="my-status-done-true my-font glyphicon glyphicon-check" aria-hidden="true" onclick="doneToggle()"></span>
    </td>

    <td id="list-title-<%= list.id %>">
      <small>
          <%= list.title %>
      </small>

    </td>

    <td class="my-operation">
      <%= link_to  edit_list_path(list), :remote => true do %>
        <button type="button" class="my-btn my-btn-transparent text-info glyphicon glyphicon-pencil" onclick="editToggle()"></button>
      <% end %>
        <button type="button" class="my-btn my-btn-transparent text-danger glyphicon glyphicon-trash" data-toggle="modal" data-target="#my-alert-<%= list.id %>" onclick="deleteCheck()"></button>
    </td>



<!-- 刪除再次確認 -->
<div class="modal fade" id="my-alert-<%= list.id %>" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title text-danger text-center">
                    即將刪除【
                    <span id="delete-content"></span>
                    】
                </h4>
            </div>
            <div class="modal-body">
                <p class="text-center">請再次確認！請再次確認！請再次確認！</p>
                <div class="alert alert-warning alert-dismissible fade in text-center" role="alert">
                    <strong>注意！</strong> 因為很重要所以要說三次
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <%= link_to  list_path(list), method: :delete, :remote => true do %>
                <button type="button" class="btn btn-danger" data-dismiss="modal">確認刪除</button>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/lists/create.js.erb
  $("#list").append("<tr> <%=j render(:partial => "tr", :locals => { :list => @list })%> </tr>");
  $("#new_list").trigger('reset');

app/views/lists/destroy.js.erb
$("#list-<%= @list.id %>").remove();

app/views/lists/edit.js.erb
var list_title = $("#list-title-<%= @list.id %>");

<% html = j( render :partial => "form", :locals => { :list => @list } ) %>

list_title.html("<%= html %>")

app/views/lists/index.html.erb
<h1 class="text-center">
  To Do List
  <span class="badge" id="badge">
      0
  </span>
</h1>

<div class="container">
  <div class="panel panel-info">
      <div class="panel-heading">
          <h3 class="panel-title">
              事項清單
          </h3>
      </div>

      <!-- 新增 -->
      <div class="panel-body">
          <%= form_for @list, remote: true do |f| %>
          <div class="input-group">
            <%= f.text_area :title, :class => "form-control" %>
            <div class="input-group-addon">
            <%= f.submit "+", :class => " my-btn btn-primary glyphicon glyphicon-plus" %>
            </div>
          </div>
          <% end %>
      </div>

      <!-- 待辦清單 -->
      <table class="my-table table table-hover">
        <tbody id="list">
          <% @lists.each do |list| %>
            <tr  id="list-<%= list.id %>">
            <%= render :partial => "tr", :locals => { :list => list } %>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

app/views/lists/update.js.erb
<% html = j( render :partial => "tr", :locals => { :list => @list } ) %>
$("#list-<%= @list.id %>").html("<%= html %>")